In [162]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [163]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [164]:
df.shape

(569, 33)

In [165]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [166]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [167]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [168]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [169]:
X_train

array([[-0.51289178, -0.30456421, -0.54290442, ..., -0.28460984,
         0.90157278, -0.83236456],
       [-0.45647397, -0.1452914 , -0.43359727, ..., -0.19189595,
         0.19167894,  0.20542921],
       [-0.23080276, -0.51536646, -0.29247685, ..., -0.26270656,
        -0.62606724, -0.42541954],
       ...,
       [-0.12642982, -0.84796557, -0.17705176, ..., -0.33111681,
        -0.58743357, -1.04843166],
       [ 0.03154003,  0.30676232,  0.02810307, ...,  0.29417686,
        -0.58099462, -0.2938761 ],
       [-1.22234567,  2.10326596, -1.22525837, ..., -0.98461469,
        -0.92386851, -0.65604038]], shape=(455, 30))

In [170]:
y_train

409    B
204    B
224    B
217    B
428    B
      ..
228    B
342    B
240    B
476    B
459    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [171]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [172]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,

### Numpy arrays to Pytorch tensors 

In [173]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [174]:
X_train_tensor.shape

torch.Size([455, 30])

In [175]:
y_train_tensor.shape

torch.Size([455])

### Defining Model

In [182]:
import torch.nn as nn

In [183]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out

    


### Important points

In [184]:
learning_rate = 0.1
epochs = 25
loss_function = nn.BCELoss()

### Training Pipeline

In [186]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

# define loop
for epoch in range(epochs): 
    # forward pass
    y_pred = model(X_train_tensor)
    
    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # Clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()
    
    # parameter update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 0.9125914573669434
Epoch: 2, Loss: 0.6672481894493103
Epoch: 3, Loss: 0.5377247929573059
Epoch: 4, Loss: 0.4618319272994995
Epoch: 5, Loss: 0.4112323522567749
Epoch: 6, Loss: 0.37451136112213135
Epoch: 7, Loss: 0.346315860748291
Epoch: 8, Loss: 0.3237851858139038
Epoch: 9, Loss: 0.30523937940597534
Epoch: 10, Loss: 0.28962013125419617
Epoch: 11, Loss: 0.2762245535850525
Epoch: 12, Loss: 0.2645655870437622
Epoch: 13, Loss: 0.25429394841194153
Epoch: 14, Loss: 0.24515190720558167
Epoch: 15, Loss: 0.23694480955600739
Epoch: 16, Loss: 0.2295224517583847
Epoch: 17, Loss: 0.22276699542999268
Epoch: 18, Loss: 0.2165844589471817
Epoch: 19, Loss: 0.21089881658554077
Epoch: 20, Loss: 0.20564788579940796
Epoch: 21, Loss: 0.20078019797801971
Epoch: 22, Loss: 0.19625268876552582
Epoch: 23, Loss: 0.1920289695262909
Epoch: 24, Loss: 0.1880781054496765
Epoch: 25, Loss: 0.1843734234571457


In [187]:
model.linear.weight

Parameter containing:
tensor([[ 0.1963,  0.1240,  0.1612,  0.2407,  0.2254,  0.1234,  0.1786,  0.1024,
          0.1446, -0.1421,  0.1352, -0.0993,  0.1907,  0.0999,  0.0247,  0.0859,
          0.1060,  0.0656,  0.0753, -0.0610,  0.4095,  0.2458,  0.3220,  0.2528,
          0.1490,  0.0240,  0.2354,  0.3092,  0.2147, -0.0837]],
       requires_grad=True)

### Evaluation

In [188]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5240073800086975
