In [38]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [39]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [40]:
df.shape

(569, 33)

In [41]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [42]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [43]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [44]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [45]:
X_train

array([[ 1.11621414,  0.2940484 ,  1.10207973, ...,  0.52698774,
         0.55343693, -0.4525188 ],
       [-0.63285716, -0.22478011, -0.6020496 , ..., -0.01661778,
         0.79185367, -0.03449245],
       [ 0.72753163,  0.48655491,  0.75362096, ...,  1.46552033,
         1.14457981,  0.64282322],
       ...,
       [ 2.14507961,  0.69784255,  2.18064259, ...,  1.97195624,
         1.49567295,  0.92866286],
       [ 1.24482232, -0.18487023,  1.21408433, ...,  0.76394399,
         1.2784851 ,  0.08639625],
       [ 0.24739441,  0.10623718,  0.15211474, ..., -0.88793533,
        -0.43452285, -1.32246553]], shape=(455, 30))

In [46]:
y_train

492    M
216    B
24     M
267    B
449    M
      ..
37     B
453    B
393    M
85     M
165    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [47]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [48]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,

### Numpy arrays to Pytorch tensors 

In [49]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [50]:
X_train_tensor.shape

torch.Size([455, 30])

In [51]:
y_train_tensor.shape

torch.Size([455])

### Defining Model

In [52]:
class MySimpleNN():

    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1 ,dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


### Important points

In [53]:
learning_rate = 0.1
epochs = 50

### Training Pipeline

In [54]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs): 
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()
    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.8542998499658205
Epoch: 2, Loss: 3.742317861388871
Epoch: 3, Loss: 3.624720340835592
Epoch: 4, Loss: 3.5015727880495637
Epoch: 5, Loss: 3.37219677085709
Epoch: 6, Loss: 3.2387601499855014
Epoch: 7, Loss: 3.104034911206992
Epoch: 8, Loss: 2.966241745860725
Epoch: 9, Loss: 2.820988515071162
Epoch: 10, Loss: 2.6718824798437684
Epoch: 11, Loss: 2.516729512488452
Epoch: 12, Loss: 2.3663453338267426
Epoch: 13, Loss: 2.220265618188292
Epoch: 14, Loss: 2.0766713003073534
Epoch: 15, Loss: 1.9315390924000406
Epoch: 16, Loss: 1.7877718715557611
Epoch: 17, Loss: 1.6491107004232084
Epoch: 18, Loss: 1.5200542420506344
Epoch: 19, Loss: 1.4032740596801627
Epoch: 20, Loss: 1.2972254210215117
Epoch: 21, Loss: 1.2059416495049562
Epoch: 22, Loss: 1.129276670701309
Epoch: 23, Loss: 1.066354171105831


Epoch: 24, Loss: 1.0156324543561088
Epoch: 25, Loss: 0.9751139067218271
Epoch: 26, Loss: 0.942702718299846
Epoch: 27, Loss: 0.9165211893225031
Epoch: 28, Loss: 0.8950427432632336
Epoch: 29, Loss: 0.8770852899853266
Epoch: 30, Loss: 0.8617568282772808
Epoch: 31, Loss: 0.8483987328926571
Epoch: 32, Loss: 0.8365357720129822
Epoch: 33, Loss: 0.8258322874777801
Epoch: 34, Loss: 0.8160546159731812
Epoch: 35, Loss: 0.8070406547279056
Epoch: 36, Loss: 0.7986768323121322
Epoch: 37, Loss: 0.7908817156029279
Epoch: 38, Loss: 0.7835948872238271
Epoch: 39, Loss: 0.7767696555099938
Epoch: 40, Loss: 0.7703683849320581
Epoch: 41, Loss: 0.764359544321468
Epoch: 42, Loss: 0.7587158497778285
Epoch: 43, Loss: 0.7534130925992534
Epoch: 44, Loss: 0.7484293914697495
Epoch: 45, Loss: 0.7437447064348347
Epoch: 46, Loss: 0.7393405148066868
Epoch: 47, Loss: 0.7351995880623337
Epoch: 48, Loss: 0.7313058325989512
Epoch: 49, Loss: 0.7276441716133554
Epoch: 50, Loss: 0.7242004540465252


In [55]:
model.bias

tensor([-0.3226], dtype=torch.float64, requires_grad=True)

### Evaluation

In [56]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5461680293083191
